### ISSUE TITLE
compilation pb with attiny85 digispark

### ISSUE THREAD

**Issue by TheoDuckLab** [ESikich/RGBLEDBlender#1]
Hello,
The examples work perfectly on Arduino Uno, Nano but on an attiny85 (Digispark) I have a compilation pb:
conversion from 'const Color*' to 'Color*' [-fpermissive]

May be i must change compilation option ... or correct the code but i ' m an absolute beginner in c++

could you explain me this pb

Thank you

The complete error message :

Arduino : 1.6.11 (Windows 10), Carte : "Digispark (Default - 16.5mhz)"

C:\Program Files (x86)\Arduino\arduino-builder -dump-prefs -logger=machine -hardware C:\Program Files (x86)\Arduino\hardware -hardware C:\Users\Stef\AppData\Local\Arduino15\packages -tools C:\Program Files (x86)\Arduino\tools-builder -tools C:\Program Files (x86)\Arduino\hardware\tools\avr -tools C:\Users\Stef\AppData\Local\Arduino15\packages -built-in-libraries C:\Program Files (x86)\Arduino\libraries -libraries Z:\Users\Stef\Documents\Arduino\libraries -fqbn=digistump:avr:digispark-tiny -ide-version=10611 -build-path C:\Users\Stef\AppData\Local\Temp\build69a18864fc1eac00a557b785b5e97bf4.tmp -warnings=none -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avr-gcc.path=C:\Users\Stef\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\4.8.1-arduino5 -prefs=runtime.tools.micronucleus.path=C:\Users\Stef\AppData\Local\Arduino15\packages\digistump\tools\micronucleus\2.0a4 -verbose Z:\Users\Stef\Documents\Arduino\libraries\RGBLEDBlender\examples\Random\Random.ino
C:\Program Files (x86)\Arduino\arduino-builder -compile -logger=machine -hardware C:\Program Files (x86)\Arduino\hardware -hardware C:\Users\Stef\AppData\Local\Arduino15\packages -tools C:\Program Files (x86)\Arduino\tools-builder -tools C:\Program Files (x86)\Arduino\hardware\tools\avr -tools C:\Users\Stef\AppData\Local\Arduino15\packages -built-in-libraries C:\Program Files (x86)\Arduino\libraries -libraries Z:\Users\Stef\Documents\Arduino\libraries -fqbn=digistump:avr:digispark-tiny -ide-version=10611 -build-path C:\Users\Stef\AppData\Local\Temp\build69a18864fc1eac00a557b785b5e97bf4.tmp -warnings=none -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avr-gcc.path=C:\Users\Stef\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\4.8.1-arduino5 -prefs=runtime.tools.micronucleus.path=C:\Users\Stef\AppData\Local\Arduino15\packages\digistump\tools\micronucleus\2.0a4 -verbose Z:\Users\Stef\Documents\Arduino\libraries\RGBLEDBlender\examples\Random\Random.ino
Using board 'digispark-tiny' from platform in folder: C:\Users\Stef\AppData\Local\Arduino15\packages\digistump\hardware\avr\1.6.7
Using core 'tiny' from platform in folder: C:\Users\Stef\AppData\Local\Arduino15\packages\digistump\hardware\avr\1.6.7
Detecting libraries used...
"C:\Users\Stef\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\4.8.1-arduino5/bin/avr-g++" -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections  -w -x c++ -E -CC -mmcu=attiny85 -DF_CPU=16500000L -DARDUINO=10611 -DARDUINO_AVR_DIGISPARK -DARDUINO_ARCH_AVR  "-IC:\Users\Stef\AppData\Local\Arduino15\packages\digistump\hardware\avr\1.6.7\cores\tiny" "-IC:\Users\Stef\AppData\Local\Arduino15\packages\digistump\hardware\avr\1.6.7\variants\digispark" "C:\Users\Stef\AppData\Local\Temp\build69a18864fc1eac00a557b785b5e97bf4.tmp\sketch\Random.ino.cpp" -o "nul"
"C:\Users\Stef\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\4.8.1-arduino5/bin/avr-g++" -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections  -w -x c++ -E -CC -mmcu=attiny85 -DF_CPU=16500000L -DARDUINO=10611 -DARDUINO_AVR_DIGISPARK -DARDUINO_ARCH_AVR  "-IC:\Users\Stef\AppData\Local\Arduino15\packages\digistump\hardware\avr\1.6.7\cores\tiny" "-IC:\Users\Stef\AppData\Local\Arduino15\packages\digistump\hardware\avr\1.6.7\variants\digispark" "-IZ:\Users\Stef\Documents\Arduino\libraries\RGBLEDBlender\src" "C:\Users\Stef\AppData\Local\Temp\build69a18864fc1eac00a557b785b5e97bf4.tmp\sketch\Random.ino.cpp" -o "nul"
"C:\Users\Stef\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\4.8.1-arduino5/bin/avr-g++" -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections  -w -x c++ -E -CC -mmcu=attiny85 -DF_CPU=16500000L -DARDUINO=10611 -DARDUINO_AVR_DIGISPARK -DARDUINO_ARCH_AVR  "-IC:\Users\Stef\AppData\Local\Arduino15\packages\digistump\hardware\avr\1.6.7\cores\tiny" "-IC:\Users\Stef\AppData\Local\Arduino15\packages\digistump\hardware\avr\1.6.7\variants\digispark" "-IZ:\Users\Stef\Documents\Arduino\libraries\RGBLEDBlender\src" "Z:\Users\Stef\Documents\Arduino\libraries\RGBLEDBlender\src\RGBLEDBlender.cpp" -o "nul"
"C:\Users\Stef\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\4.8.1-arduino5/bin/avr-g++" -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections  -w -x c++ -E -CC -mmcu=attiny85 -DF_CPU=16500000L -DARDUINO=10611 -DARDUINO_AVR_DIGISPARK -DARDUINO_ARCH_AVR  "-IC:\Users\Stef\AppData\Local\Arduino15\packages\digistump\hardware\avr\1.6.7\cores\tiny" "-IC:\Users\Stef\AppData\Local\Arduino15\packages\digistump\hardware\avr\1.6.7\variants\digispark" "-IZ:\Users\Stef\Documents\Arduino\libraries\RGBLEDBlender\src" "C:\Users\Stef\AppData\Local\Temp\build69a18864fc1eac00a557b785b5e97bf4.tmp\sketch\Random.ino.cpp" -o "nul"
Generating function prototypes...
"C:\Users\Stef\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\4.8.1-arduino5/bin/avr-g++" -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections  -w -x c++ -E -CC -mmcu=attiny85 -DF_CPU=16500000L -DARDUINO=10611 -DARDUINO_AVR_DIGISPARK -DARDUINO_ARCH_AVR  "-IC:\Users\Stef\AppData\Local\Arduino15\packages\digistump\hardware\avr\1.6.7\cores\tiny" "-IC:\Users\Stef\AppData\Local\Arduino15\packages\digistump\hardware\avr\1.6.7\variants\digispark" "-IZ:\Users\Stef\Documents\Arduino\libraries\RGBLEDBlender\src" "C:\Users\Stef\AppData\Local\Temp\build69a18864fc1eac00a557b785b5e97bf4.tmp\sketch\Random.ino.cpp" -o "C:\Users\Stef\AppData\Local\Temp\build69a18864fc1eac00a557b785b5e97bf4.tmp\preproc\ctags_target_for_gcc_minus_e.cpp"
"C:\Program Files (x86)\Arduino\tools-builder\ctags\5.8-arduino10/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives "C:\Users\Stef\AppData\Local\Temp\build69a18864fc1eac00a557b785b5e97bf4.tmp\preproc\ctags_target_for_gcc_minus_e.cpp"
Compilation du croquis...
"C:\Users\Stef\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\4.8.1-arduino5/bin/avr-g++" -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -MMD -mmcu=attiny85 -DF_CPU=16500000L -DARDUINO=10611 -DARDUINO_AVR_DIGISPARK -DARDUINO_ARCH_AVR  "-IC:\Users\Stef\AppData\Local\Arduino15\packages\digistump\hardware\avr\1.6.7\cores\tiny" "-IC:\Users\Stef\AppData\Local\Arduino15\packages\digistump\hardware\avr\1.6.7\variants\digispark" "-IZ:\Users\Stef\Documents\Arduino\libraries\RGBLEDBlender\src" "C:\Users\Stef\AppData\Local\Temp\build69a18864fc1eac00a557b785b5e97bf4.tmp\sketch\Random.ino.cpp" -o "C:\Users\Stef\AppData\Local\Temp\build69a18864fc1eac00a557b785b5e97bf4.tmp\sketch\Random.ino.cpp.o"
Compiling libraries...
Compiling library "RGBLEDBlender"
"C:\Users\Stef\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\4.8.1-arduino5/bin/avr-g++" -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -MMD -mmcu=attiny85 -DF_CPU=16500000L -DARDUINO=10611 -DARDUINO_AVR_DIGISPARK -DARDUINO_ARCH_AVR  "-IC:\Users\Stef\AppData\Local\Arduino15\packages\digistump\hardware\avr\1.6.7\cores\tiny" "-IC:\Users\Stef\AppData\Local\Arduino15\packages\digistump\hardware\avr\1.6.7\variants\digispark" "-IZ:\Users\Stef\Documents\Arduino\libraries\RGBLEDBlender\src" "Z:\Users\Stef\Documents\Arduino\libraries\RGBLEDBlender\src\RGBLEDBlender.cpp" -o "C:\Users\Stef\AppData\Local\Temp\build69a18864fc1eac00a557b785b5e97bf4.tmp\libraries\RGBLEDBlender\RGBLEDBlender.cpp.o"
Z:\Users\Stef\Documents\Arduino\libraries\RGBLEDBlender\src\RGBLEDBlender.cpp: In member function 'void RGBLEDBlender::RandomCycle(const Color*, uint8_t, uint32_t)':

Z:\Users\Stef\Documents\Arduino\libraries\RGBLEDBlender\src\RGBLEDBlender.cpp:68:17: error: invalid conversion from 'const Color*' to 'Color*' [-fpermissive]

     color_list_ = color_list;

                 ^

Z:\Users\Stef\Documents\Arduino\libraries\RGBLEDBlender\src\RGBLEDBlender.cpp: In member function 'void RGBLEDBlender::Cycle(const Color*, uint8_t, uint32_t)':

Z:\Users\Stef\Documents\Arduino\libraries\RGBLEDBlender\src\RGBLEDBlender.cpp:76:17: error: invalid conversion from 'const Color*' to 'Color*' [-fpermissive]

     color_list_ = color_list;

                 ^

Utilisation de la bibliothèque RGBLEDBlender version 1.1.2 dans le dossier: Z:\Users\Stef\Documents\Arduino\libraries\RGBLEDBlender 
exit status 1
Erreur de compilation pour la carte Digispark (Default - 16.5mhz)

**Comment by ESikich** [comment]
Post your code and I can try to help.

**Comment by TheoDuckLab** [comment]
It's a compilation pb with all the exemples you give, and i have the problem only on attiny85, not on arduino. I try older release and I have an other compilation pb (not this one  "conversion from 'const Color*' to 'Color*' [-fpermissive]")  ... may be compilation option is more restrictive with attiny ?

    Color color_list[6] = {_RED, _ORANGE, _YELLOW, _GREEN, _BLUE, _PURPLE};
    RGBLEDBlender my_blender(2, 3, 4);
    while(true){
        //Fade randomly for 1000 ms
        my_blender.RandomCycle(color_list, 6, 1000);
